DROP TABLE IF EXISTS forum;

CREATE TABLE forum (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(100) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT NOW()
) DEFAULT CHARACTER SET=utf8mb4;
